# ---- builder ----
FROM node:20-alpine AS builder
WORKDIR /app

# copia de manifiestos (npm)
COPY package*.json ./
RUN npm ci --ignore-scripts

# resto del proyecto
COPY . .
RUN npm run build

# ---- runner (Node) ----
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production \
    PORT=3000

# sólo lo necesario para correr Next en modo standalone
COPY --from=builder /app/.next/standalone ./ 
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "server.js"]
